export const tasks = [
  {
    id: "task-1",
    title: "Implement login functionality",
    description:
      "Create a login form with email and password fields. Implement validation and error handling. Connect to the authentication API.",
    status: "todo",
    priority: "High",
    assignee: "John Doe",
    dueDate: "2023-12-15",
    createdAt: "2023-12-01",
    subtasks: [
      { title: "Design login form", completed: true },
      { title: "Implement form validation", completed: false },
      { title: "Connect to auth API", completed: false },
    ],
  },
  {
    id: "task-2",
    title: "Design dashboard layout",
    description:
      "Create a responsive dashboard layout with sidebar navigation, header, and main content area. Ensure it works well on mobile devices.",
    status: "inprogress",
    priority: "Medium",
    assignee: "Jane Smith",
    dueDate: "2023-12-10",
    createdAt: "2023-12-02",
    subtasks: [
      { title: "Sketch wireframes", completed: true },
      { title: "Create high-fidelity design", completed: true },
      { title: "Implement responsive layout", completed: false },
    ],
  },
  {
    id: "task-3",
    title: "Fix payment processing bug",
    description:
      "There is an issue with payment processing where some transactions are failing silently. Investigate the cause and implement a fix.",
    status: "inreview",
    priority: "High",
    assignee: "Mike Johnson",
    dueDate: "2023-12-08",
    createdAt: "2023-12-03",
    subtasks: [
      { title: "Reproduce the issue", completed: true },
      { title: "Debug payment flow", completed: true },
      { title: "Implement fix", completed: true },
      { title: "Write tests", completed: false },
    ],
  },
  {
    id: "task-4",
    title: "Update user documentation",
    description:
      "Update the user documentation to reflect recent changes to the application. Include screenshots and step-by-step instructions.",
    status: "done",
    priority: "Low",
    assignee: "Sarah Williams",
    dueDate: "2023-12-05",
    createdAt: "2023-12-01",
    subtasks: [
      { title: "Review existing documentation", completed: true },
      { title: "Update content", completed: true },
      { title: "Add screenshots", completed: true },
      { title: "Publish changes", completed: true },
    ],
  },
  {
    id: "task-5",
    title: "Optimize database queries",
    description:
      "Several pages are loading slowly due to inefficient database queries. Identify the slow queries and optimize them for better performance.",
    status: "todo",
    priority: "Medium",
    assignee: "David Chen",
    dueDate: "2023-12-20",
    createdAt: "2023-12-04",
    subtasks: [
      { title: "Profile application performance", completed: false },
      { title: "Identify slow queries", completed: false },
      { title: "Optimize queries", completed: false },
      { title: "Measure improvements", completed: false },
    ],
  },
  {
    id: "task-6",
    title: "Implement dark mode",
    description:
      "Add a dark mode option to the application. Create a toggle in the user settings and ensure all components support both light and dark themes.",
    status: "inprogress",
    priority: "Low",
    assignee: "Emily Taylor",
    dueDate: "2023-12-18",
    createdAt: "2023-12-03",
    subtasks: [
      { title: "Create color palette for dark mode", completed: true },
      { title: "Implement theme toggle", completed: true },
      { title: "Update components for dark mode", completed: false },
      { title: "Test on different devices", completed: false },
    ],
  },
  {
    id: "task-7",
    title: "Add export to CSV feature",
    description:
      "Users need to be able to export their data to CSV format. Implement this feature in the reports section of the application.",
    status: "todo",
    priority: "Medium",
    assignee: "Alex Johnson",
    dueDate: "2023-12-22",
    createdAt: "2023-12-05",
    subtasks: [
      { title: "Design UI for export options", completed: false },
      { title: "Implement CSV generation", completed: false },
      { title: "Add download functionality", completed: false },
      { title: "Test with large datasets", completed: false },
    ],
  },
  {
    id: "task-8",
    title: "Refactor authentication service",
    description:
      "The current authentication service has become difficult to maintain. Refactor it to improve code quality and testability.",
    status: "inreview",
    priority: "High",
    assignee: "Ryan Miller",
    dueDate: "2023-12-12",
    createdAt: "2023-12-02",
    subtasks: [
      { title: "Analyze current implementation", completed: true },
      { title: "Design new architecture", completed: true },
      { title: "Implement refactored service", completed: true },
      { title: "Write unit tests", completed: false },
      { title: "Update documentation", completed: false },
    ],
  },
  {
    id: "task-9",
    title: "Create onboarding tutorial",
    description:
      "New users need better guidance when they first use the application. Create an interactive onboarding tutorial that highlights key features.",
    status: "done",
    priority: "Medium",
    assignee: "Lisa Anderson",
    dueDate: "2023-12-07",
    createdAt: "2023-11-30",
    subtasks: [
      { title: "Identify key features to highlight", completed: true },
      { title: "Design tutorial UI", completed: true },
      { title: "Implement interactive elements", completed: true },
      { title: "Test with new users", completed: true },
      { title: "Incorporate feedback", completed: true },
    ],
  },
  {
    id: "task-10",
    title: "Improve accessibility",
    description:
      "Conduct an accessibility audit and make necessary improvements to ensure the application is usable by people with disabilities.",
    status: "inprogress",
    priority: "High",
    assignee: "Tom Wilson",
    dueDate: "2023-12-25",
    createdAt: "2023-12-05",
    subtasks: [
      { title: "Conduct accessibility audit", completed: true },
      { title: "Fix keyboard navigation issues", completed: false },
      { title: "Improve screen reader compatibility", completed: false },
      { title: "Add ARIA attributes where needed", completed: false },
      { title: "Test with assistive technologies", completed: false },
    ],
  },
  {
    id: "task-11",
    title: "Set up CI/CD pipeline",
    description:
      "Set up a continuous integration and deployment pipeline to automate testing and deployment processes.",
    status: "done",
    priority: "Medium",
    assignee: "Chris Martin",
    dueDate: "2023-12-06",
    createdAt: "2023-11-29",
    subtasks: [
      { title: "Choose CI/CD tools", completed: true },
      { title: "Configure build process", completed: true },
      { title: "Set up automated testing", completed: true },
      { title: "Configure deployment process", completed: true },
      { title: "Document the pipeline", completed: true },
    ],
  },
  {
    id: "task-12",
    title: "Implement real-time notifications",
    description:
      "Add real-time notifications to alert users of important events, such as new messages or updates to their tasks.",
    status: "todo",
    priority: "Low",
    assignee: "Sophia Lee",
    dueDate: "2023-12-28",
    createdAt: "2023-12-06",
    subtasks: [
      { title: "Research notification solutions", completed: false },
      { title: "Design notification UI", completed: false },
      { title: "Implement backend service", completed: false },
      { title: "Connect frontend to notification service", completed: false },
      { title: "Test notification delivery", completed: false },
    ],
  },
]
